version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Location of package manifests, relative to the repo root
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "monthly"
